version: "3.9"

volumes:
  db_services_data:
  localstack_data:
networks:
  order-system-network:
    external: false

services:
  localstack:
    image: localstack/localstack:2.2.0
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG-}
      - LOCALSTACK_PERSISTENCE=1
    volumes:
      - "localstack_data:/var/lib/localstack"
    networks:
      - order-system-network

  db-services:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_services_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - order-system-network

  catalogue:
    build: services/catalogue/
    ports:
      - "8180:8080"
    depends_on:
      - db-services
    networks:
      - order-system-network

  # pricing:
  #   build: services/pricing/
  #   ports:
  #     - "8182:8080"
  #   depends_on:
  #     - db-services
  #   networks:
  #     - order-system-network

  # product-search:
  #   build: services/product-search/
  #   ports:
  #     - "8183:8080"
  #   depends_on:
  #     - db-services
  #   networks:
  #     - order-system-network

  # order:
  #   build: services/order/
  #   ports:
  #     - "8184:8080"
  #   depends_on:
  #     - db-services
  #   networks:
  #     - order-system-network
