volumes:
  db_services_data:
  localstack_data:
networks:
  order-system-network:
    external: false

services:
  localstack:
    image: localstack/localstack:2.2.0
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG-}
      - LOCALSTACK_PERSISTENCE=1
    volumes:
      - "localstack_data:/var/lib/localstack"
    networks:
      - order-system-network

  services-db:
    image: postgres:16.0-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env.template
    volumes:
      - db_services_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - order-system-network

  catalogue-migrations:
    build: services/catalogue/
    volumes:
      - ./services/catalogue/migrations:/app/migrations
      - ./services/catalogue/src:/app/src
    env_file:
      - .env.template
    depends_on:
      - services-db
    command: bash -c "while !</dev/tcp/services-db/5432; do sleep 1; done; alembic -c migrations/alembic/alembic.ini upgrade head"
    networks:
      - order-system-network

  catalogue:
    build: services/catalogue/
    ports:
      - "8180:8080"
    depends_on:
      - services-db
    networks:
      - order-system-network

  # pricing:
  #   build: services/pricing/
  #   ports:
  #     - "8182:8080"
  #   depends_on:
  #     - services-db
  #   networks:
  #     - order-system-network

  # product-search:
  #   build: services/product-search/
  #   ports:
  #     - "8183:8080"
  #   depends_on:
  #     - services-db
  #   networks:
  #     - order-system-network

  # order:
  #   build: services/order/
  #   ports:
  #     - "8184:8080"
  #   depends_on:
  #     - services-db
  #   networks:
  #     - order-system-network
