"""feat: add entities

Revision ID: f272a7db175c
Revises:
Create Date: 2024-07-07 14:43:55.547297

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f272a7db175c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS catalogue")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Category",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="catalogue",
    )
    op.create_table(
        "Inventory",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("reserved", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="catalogue",
    )
    op.create_table(
        "Price",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("discount_percent", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="catalogue",
    )
    op.create_table(
        "Product",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("image_url", sa.String(length=255), nullable=False),
        sa.Column("price_id", sa.UUID(), nullable=True),
        sa.Column("inventory_id", sa.UUID(), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["catalogue.Category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["inventory_id"],
            ["catalogue.Inventory.id"],
        ),
        sa.ForeignKeyConstraint(
            ["price_id"],
            ["catalogue.Price.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sku"),
        schema="catalogue",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Product", schema="catalogue")
    op.drop_table("Price", schema="catalogue")
    op.drop_table("Inventory", schema="catalogue")
    op.drop_table("Category", schema="catalogue")
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS catalogue")
