CREATE DATABASE "catalogue";
CREATE DATABASE "order";

CREATE USER catalogue_app WITH PASSWORD '123abc';
CREATE USER order_app WITH PASSWORD '123abc';

GRANT ALL PRIVILEGES ON DATABASE "catalogue" TO catalogue_app;
GRANT ALL PRIVILEGES ON DATABASE "order" TO order_app;

\c catalogue
GRANT ALL PRIVILEGES ON SCHEMA public TO catalogue_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO catalogue_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO catalogue_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO catalogue_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO catalogue_app;

\c order
GRANT ALL PRIVILEGES ON SCHEMA public TO order_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO order_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO order_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO order_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO order_app;
